#include "led_panel.h"

#define LED_PANEL_MAP_ENTRY(index)                                                       \
	{(uint8_t)((index) / BSP_TM3100_CHANNEL_PER_CHIP),                                   \
	 (uint8_t)((index) % BSP_TM3100_CHANNEL_PER_CHIP)}

static const stc_led_panel_map_t s_astLedPanelMap[BSP_TM3100_LED_COUNT] = {
	LED_PANEL_MAP_ENTRY(0u),   LED_PANEL_MAP_ENTRY(1u),	  LED_PANEL_MAP_ENTRY(2u),
	LED_PANEL_MAP_ENTRY(3u),   LED_PANEL_MAP_ENTRY(4u),	  LED_PANEL_MAP_ENTRY(5u),
	LED_PANEL_MAP_ENTRY(6u),   LED_PANEL_MAP_ENTRY(7u),	  LED_PANEL_MAP_ENTRY(8u),
	LED_PANEL_MAP_ENTRY(9u),   LED_PANEL_MAP_ENTRY(10u),  LED_PANEL_MAP_ENTRY(11u),
	LED_PANEL_MAP_ENTRY(12u),  LED_PANEL_MAP_ENTRY(13u),  LED_PANEL_MAP_ENTRY(14u),
	LED_PANEL_MAP_ENTRY(15u),  LED_PANEL_MAP_ENTRY(16u),  LED_PANEL_MAP_ENTRY(17u),
	LED_PANEL_MAP_ENTRY(18u),  LED_PANEL_MAP_ENTRY(19u),  LED_PANEL_MAP_ENTRY(20u),
	LED_PANEL_MAP_ENTRY(21u),  LED_PANEL_MAP_ENTRY(22u),  LED_PANEL_MAP_ENTRY(23u),
	LED_PANEL_MAP_ENTRY(24u),  LED_PANEL_MAP_ENTRY(25u),  LED_PANEL_MAP_ENTRY(26u),
	LED_PANEL_MAP_ENTRY(27u),  LED_PANEL_MAP_ENTRY(28u),  LED_PANEL_MAP_ENTRY(29u),
	LED_PANEL_MAP_ENTRY(30u),  LED_PANEL_MAP_ENTRY(31u),  LED_PANEL_MAP_ENTRY(32u),
	LED_PANEL_MAP_ENTRY(33u),  LED_PANEL_MAP_ENTRY(34u),  LED_PANEL_MAP_ENTRY(35u),
	LED_PANEL_MAP_ENTRY(36u),  LED_PANEL_MAP_ENTRY(37u),  LED_PANEL_MAP_ENTRY(38u),
	LED_PANEL_MAP_ENTRY(39u),  LED_PANEL_MAP_ENTRY(40u),  LED_PANEL_MAP_ENTRY(41u),
	LED_PANEL_MAP_ENTRY(42u),  LED_PANEL_MAP_ENTRY(43u),  LED_PANEL_MAP_ENTRY(44u),
	LED_PANEL_MAP_ENTRY(45u),  LED_PANEL_MAP_ENTRY(46u),  LED_PANEL_MAP_ENTRY(47u),
	LED_PANEL_MAP_ENTRY(48u),  LED_PANEL_MAP_ENTRY(49u),  LED_PANEL_MAP_ENTRY(50u),
	LED_PANEL_MAP_ENTRY(51u),  LED_PANEL_MAP_ENTRY(52u),  LED_PANEL_MAP_ENTRY(53u),
	LED_PANEL_MAP_ENTRY(54u),  LED_PANEL_MAP_ENTRY(55u),  LED_PANEL_MAP_ENTRY(56u),
	LED_PANEL_MAP_ENTRY(57u),  LED_PANEL_MAP_ENTRY(58u),  LED_PANEL_MAP_ENTRY(59u),
	LED_PANEL_MAP_ENTRY(60u),  LED_PANEL_MAP_ENTRY(61u),  LED_PANEL_MAP_ENTRY(62u),
	LED_PANEL_MAP_ENTRY(63u),  LED_PANEL_MAP_ENTRY(64u),  LED_PANEL_MAP_ENTRY(65u),
	LED_PANEL_MAP_ENTRY(66u),  LED_PANEL_MAP_ENTRY(67u),  LED_PANEL_MAP_ENTRY(68u),
	LED_PANEL_MAP_ENTRY(69u),  LED_PANEL_MAP_ENTRY(70u),  LED_PANEL_MAP_ENTRY(71u),
	LED_PANEL_MAP_ENTRY(72u),  LED_PANEL_MAP_ENTRY(73u),  LED_PANEL_MAP_ENTRY(74u),
	LED_PANEL_MAP_ENTRY(75u),  LED_PANEL_MAP_ENTRY(76u),  LED_PANEL_MAP_ENTRY(77u),
	LED_PANEL_MAP_ENTRY(78u),  LED_PANEL_MAP_ENTRY(79u),  LED_PANEL_MAP_ENTRY(80u),
	LED_PANEL_MAP_ENTRY(81u),  LED_PANEL_MAP_ENTRY(82u),  LED_PANEL_MAP_ENTRY(83u),
	LED_PANEL_MAP_ENTRY(84u),  LED_PANEL_MAP_ENTRY(85u),  LED_PANEL_MAP_ENTRY(86u),
	LED_PANEL_MAP_ENTRY(87u),  LED_PANEL_MAP_ENTRY(88u),  LED_PANEL_MAP_ENTRY(89u),
	LED_PANEL_MAP_ENTRY(90u),  LED_PANEL_MAP_ENTRY(91u),  LED_PANEL_MAP_ENTRY(92u),
	LED_PANEL_MAP_ENTRY(93u),  LED_PANEL_MAP_ENTRY(94u),  LED_PANEL_MAP_ENTRY(95u),
	LED_PANEL_MAP_ENTRY(96u),  LED_PANEL_MAP_ENTRY(97u),  LED_PANEL_MAP_ENTRY(98u),
	LED_PANEL_MAP_ENTRY(99u),  LED_PANEL_MAP_ENTRY(100u), LED_PANEL_MAP_ENTRY(101u),
	LED_PANEL_MAP_ENTRY(102u), LED_PANEL_MAP_ENTRY(103u), LED_PANEL_MAP_ENTRY(104u),
	LED_PANEL_MAP_ENTRY(105u), LED_PANEL_MAP_ENTRY(106u), LED_PANEL_MAP_ENTRY(107u),
	LED_PANEL_MAP_ENTRY(108u), LED_PANEL_MAP_ENTRY(109u), LED_PANEL_MAP_ENTRY(110u),
	LED_PANEL_MAP_ENTRY(111u), LED_PANEL_MAP_ENTRY(112u), LED_PANEL_MAP_ENTRY(113u),
	LED_PANEL_MAP_ENTRY(114u), LED_PANEL_MAP_ENTRY(115u), LED_PANEL_MAP_ENTRY(116u),
	LED_PANEL_MAP_ENTRY(117u), LED_PANEL_MAP_ENTRY(118u), LED_PANEL_MAP_ENTRY(119u),
	LED_PANEL_MAP_ENTRY(120u), LED_PANEL_MAP_ENTRY(121u), LED_PANEL_MAP_ENTRY(122u),
	LED_PANEL_MAP_ENTRY(123u), LED_PANEL_MAP_ENTRY(124u), LED_PANEL_MAP_ENTRY(125u),
	LED_PANEL_MAP_ENTRY(126u), LED_PANEL_MAP_ENTRY(127u), LED_PANEL_MAP_ENTRY(128u),
	LED_PANEL_MAP_ENTRY(129u), LED_PANEL_MAP_ENTRY(130u), LED_PANEL_MAP_ENTRY(131u),
	LED_PANEL_MAP_ENTRY(132u), LED_PANEL_MAP_ENTRY(133u), LED_PANEL_MAP_ENTRY(134u),
	LED_PANEL_MAP_ENTRY(135u), LED_PANEL_MAP_ENTRY(136u), LED_PANEL_MAP_ENTRY(137u),
	LED_PANEL_MAP_ENTRY(138u), LED_PANEL_MAP_ENTRY(139u), LED_PANEL_MAP_ENTRY(140u),
	LED_PANEL_MAP_ENTRY(141u), LED_PANEL_MAP_ENTRY(142u), LED_PANEL_MAP_ENTRY(143u),
	LED_PANEL_MAP_ENTRY(144u), LED_PANEL_MAP_ENTRY(145u), LED_PANEL_MAP_ENTRY(146u),
	LED_PANEL_MAP_ENTRY(147u), LED_PANEL_MAP_ENTRY(148u), LED_PANEL_MAP_ENTRY(149u),
	LED_PANEL_MAP_ENTRY(150u), LED_PANEL_MAP_ENTRY(151u), LED_PANEL_MAP_ENTRY(152u),
	LED_PANEL_MAP_ENTRY(153u), LED_PANEL_MAP_ENTRY(154u), LED_PANEL_MAP_ENTRY(155u),
	LED_PANEL_MAP_ENTRY(156u), LED_PANEL_MAP_ENTRY(157u), LED_PANEL_MAP_ENTRY(158u),
	LED_PANEL_MAP_ENTRY(159u), LED_PANEL_MAP_ENTRY(160u), LED_PANEL_MAP_ENTRY(161u),
	LED_PANEL_MAP_ENTRY(162u), LED_PANEL_MAP_ENTRY(163u), LED_PANEL_MAP_ENTRY(164u),
	LED_PANEL_MAP_ENTRY(165u), LED_PANEL_MAP_ENTRY(166u), LED_PANEL_MAP_ENTRY(167u),
	LED_PANEL_MAP_ENTRY(168u), LED_PANEL_MAP_ENTRY(169u), LED_PANEL_MAP_ENTRY(170u),
	LED_PANEL_MAP_ENTRY(171u), LED_PANEL_MAP_ENTRY(172u), LED_PANEL_MAP_ENTRY(173u),
	LED_PANEL_MAP_ENTRY(174u), LED_PANEL_MAP_ENTRY(175u), LED_PANEL_MAP_ENTRY(176u),
	LED_PANEL_MAP_ENTRY(177u), LED_PANEL_MAP_ENTRY(178u), LED_PANEL_MAP_ENTRY(179u),
	LED_PANEL_MAP_ENTRY(180u), LED_PANEL_MAP_ENTRY(181u), LED_PANEL_MAP_ENTRY(182u),
	LED_PANEL_MAP_ENTRY(183u), LED_PANEL_MAP_ENTRY(184u), LED_PANEL_MAP_ENTRY(185u),
	LED_PANEL_MAP_ENTRY(186u), LED_PANEL_MAP_ENTRY(187u), LED_PANEL_MAP_ENTRY(188u),
	LED_PANEL_MAP_ENTRY(189u), LED_PANEL_MAP_ENTRY(190u), LED_PANEL_MAP_ENTRY(191u),
	LED_PANEL_MAP_ENTRY(192u), LED_PANEL_MAP_ENTRY(193u), LED_PANEL_MAP_ENTRY(194u),
	LED_PANEL_MAP_ENTRY(195u), LED_PANEL_MAP_ENTRY(196u), LED_PANEL_MAP_ENTRY(197u),
	LED_PANEL_MAP_ENTRY(198u), LED_PANEL_MAP_ENTRY(199u), LED_PANEL_MAP_ENTRY(200u),
	LED_PANEL_MAP_ENTRY(201u), LED_PANEL_MAP_ENTRY(202u), LED_PANEL_MAP_ENTRY(203u),
	LED_PANEL_MAP_ENTRY(204u), LED_PANEL_MAP_ENTRY(205u), LED_PANEL_MAP_ENTRY(206u),
	LED_PANEL_MAP_ENTRY(207u), LED_PANEL_MAP_ENTRY(208u), LED_PANEL_MAP_ENTRY(209u),
	LED_PANEL_MAP_ENTRY(210u), LED_PANEL_MAP_ENTRY(211u), LED_PANEL_MAP_ENTRY(212u),
	LED_PANEL_MAP_ENTRY(213u), LED_PANEL_MAP_ENTRY(214u), LED_PANEL_MAP_ENTRY(215u),
	LED_PANEL_MAP_ENTRY(216u), LED_PANEL_MAP_ENTRY(217u), LED_PANEL_MAP_ENTRY(218u),
	LED_PANEL_MAP_ENTRY(219u), LED_PANEL_MAP_ENTRY(220u), LED_PANEL_MAP_ENTRY(221u),
	LED_PANEL_MAP_ENTRY(222u), LED_PANEL_MAP_ENTRY(223u), LED_PANEL_MAP_ENTRY(224u),
	LED_PANEL_MAP_ENTRY(225u), LED_PANEL_MAP_ENTRY(226u), LED_PANEL_MAP_ENTRY(227u),
	LED_PANEL_MAP_ENTRY(228u), LED_PANEL_MAP_ENTRY(229u), LED_PANEL_MAP_ENTRY(230u),
	LED_PANEL_MAP_ENTRY(231u), LED_PANEL_MAP_ENTRY(232u), LED_PANEL_MAP_ENTRY(233u),
	LED_PANEL_MAP_ENTRY(234u), LED_PANEL_MAP_ENTRY(235u), LED_PANEL_MAP_ENTRY(236u),
	LED_PANEL_MAP_ENTRY(237u), LED_PANEL_MAP_ENTRY(238u), LED_PANEL_MAP_ENTRY(239u),
};

static en_result_t LedPanel_SetImpl(uint16_t led_id, boolean_t on) {
	const stc_led_panel_map_t *pstcMap;

	if (led_id >= g_stcLedPanel.count) {
		return ErrorInvalidParameter;
	}

	pstcMap = &g_stcLedPanel.map[led_id];

	return Bsp_Tm3100Led_SetChipChannel(pstcMap->chip, pstcMap->channel, on);
}

static const stc_led_panel_ops_t s_stcLedPanelOps = {
	Bsp_Tm3100Led_Init,			LedPanel_SetImpl,	Bsp_Tm3100Led_SetChipChannel,
	Bsp_Tm3100Led_Clear,		Bsp_Tm3100Led_Fill, Bsp_Tm3100Led_Refresh,
	Bsp_Tm3100Led_OutputEnable,
};

stc_led_panel_t g_stcLedPanel = {
	&s_stcLedPanelOps,
	s_astLedPanelMap,
	BSP_TM3100_LED_COUNT,
};

en_result_t LedPanel_Init(void) {
	return g_stcLedPanel.ops->init();
}

en_result_t LedPanel_Set(uint16_t led_id, boolean_t on) {
	return g_stcLedPanel.ops->set(led_id, on);
}

en_result_t LedPanel_SetChipChannel(uint8_t chip, uint8_t channel, boolean_t on) {
	return g_stcLedPanel.ops->set_chip_channel(chip, channel, on);
}

en_result_t LedPanel_Clear(void) {
	return g_stcLedPanel.ops->clear();
}

en_result_t LedPanel_Fill(void) {
	return g_stcLedPanel.ops->fill();
}

en_result_t LedPanel_Refresh(void) {
	return g_stcLedPanel.ops->refresh();
}

en_result_t LedPanel_OutputEnable(boolean_t enable) {
	return g_stcLedPanel.ops->output_enable(enable);
}
